name: Metrics
on:
  # Schedule daily updates
 schedule: # 03:00 JST == 18:00 UTC
    - cron: "0 18 * * *"
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
